kind: PersistentVolumeClaim
apiVersion: v1
 
metadata:
  name: postgres-pv-claim
  labels:
    app: postgresdb
 
spec:
  #storageClassName: local-path
  accessModes:
    - ReadWriteOnce
 
  resources:
    requests:
      storage: 100Mi
