apiVersion: v1
kind: ConfigMap
metadata:
  name: crapi-workshop-configmap
  labels:
    app: crapi-workshop
data:
    DB_HOST: postgresdb
    DB_DRIVER: postgres
    JWT_SECRET: crapi
    DB_USER: admin
    DB_PASSWORD: crapisecretpassword
    DB_NAME: crapi
    DB_PORT: 5432 
    SECRET_KEY: crapi
