kind: PersistentVolumeClaim
apiVersion: v1
 
metadata:
  name: mailhog-pv-claim
  labels:
    app: mailhog
 
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
 
  resources:
    requests:
      storage: 100Mi
